version: "3.3"
services:

  cicdworkshop:
    image: cicdworkshop
    ports:
      - 80:80
    container_name: cicdworkshop
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - cicdworkshop_net

networks:
  cicdworkshop_net:
